//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Single2013.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BinSizeIndex {
            get {
                return ((int)(this["BinSizeIndex"]));
            }
            set {
                this["BinSizeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ZoomModeIndex {
            get {
                return ((int)(this["ZoomModeIndex"]));
            }
            set {
                this["ZoomModeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\user\\tir\\data")]
        public string PMASavePath {
            get {
                return ((string)(this["PMASavePath"]));
            }
            set {
                this["PMASavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hel")]
        public string PMAhead {
            get {
                return ((string)(this["PMAhead"]));
            }
            set {
                this["PMAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Green</string>
  <string>dev1/port0/line24</string>
  <string>Red</string>
  <string>dev1/port0/line20</string>
  <string>Blue</string>
  <string>dev1/port0/line28</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Lasers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Lasers"]));
            }
            set {
                this["Lasers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Green</string>
  <string>dev1/ctr3</string>
  <string>/dev1/20MhzTimebase</string>
  <string>/dev1/PFI35</string>
  <string>Red</string>
  <string>dev1/ctr4</string>
  <string>/dev1/20MhzTimebase</string>
  <string>/dev1/PFI35</string>
  <string>Blue</string>
  <string>dev1/ctr2</string>
  <string>/dev1/20MhzTimebase</string>
  <string>/dev1/PFI35</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Counters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Counters"]));
            }
            set {
                this["Counters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\shrcol.tbl")]
        public string Colortable {
            get {
                return ((string)(this["Colortable"]));
            }
            set {
                this["Colortable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CCDModelIndex {
            get {
                return ((int)(this["CCDModelIndex"]));
            }
            set {
                this["CCDModelIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public int ImagingWidth {
            get {
                return ((int)(this["ImagingWidth"]));
            }
            set {
                this["ImagingWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public int ImagingHeight {
            get {
                return ((int)(this["ImagingHeight"]));
            }
            set {
                this["ImagingHeight"] = value;
            }
        }
    }
}
